### ISSUE TITLE
Option to serialise / deserialise to unitless numeric values

### ISSUE THREAD

**Issue by Owen-OptiGrid** [tylerh111/pydantic-pint#1]
Thanks for creating this package - I love the idea of combining Pydantic and Pint.

I was wondering if you'd be open to the idea of supporting deserialising from or serialising to unitless numeric values - to support the case where Pydantic models are being persisted to a database with numeric attributes / columns that won't take a unit.

I was thinking if deserialising plain unitless numeric values whether you could just assume the values where in the typehinted units of measure.

**Comment by tylerh111** [comment]
Thanks! It was interesting working with the lower level pydantic schemas.

That sounds good. I'm thinking we could add an option to `ser_mode` in `PydanticPintQuantity`'s constructor. You'd still get unit validation, modification, etc. Something like `num` or `number`. Since we don't need to serialize the units, we don't have to be tied to a string.

What also might be good is to have a enum of the different serialization modes. As well as being able to specify the serialization mode in `PydanticPintQuantity.serialize` (if `None`, use `self.ser_mode`). That can be done separately.

**Comment by tylerh111** [comment]
Reading over this issue again, we do have validation (deserialization) from numeric values. You will want to set `strict=False` to allow numbers as inputs.

For serialization, I added `ser_mode="number"` to allow serializing to a number. Doing this will obviously drop the units, but if units are consistent throughout the program and any external services (e.g. databases), then won't be an issue. That was the reason I didn't implement that to being with. However, so long as it's an "opt-in" feature, it's okay to add it. The note is the documentation is still there (regarding serialization to a number).

A PR will be up shortly.
