### ISSUE TITLE
Restrict only dimensionality

### ISSUE THREAD

**Issue by lcnittl** [tylerh111/pydantic-pint#4]
Thanks for providing this library!

We are looking for something slighlty more flexible, and so I was wondering whether you consider to not only allow restriction to fixed units, but also more losely to dimensionalities. This would look sth like this:

```py
type Length = Annotated[PlainQuantity, DimensionalityRestrictedQuantity({"[length]": 1})]


class Box(BaseModel):
    length: Length
    width: Length


box = Box(
    length="4 in",
    width="2 m",
)

print(box)
#> length=<Quantity(4, 'inch')> width=<Quantity(2, 'meter')>
```

The important bit is, that any quantity with matching dimensionality is accepted and neither of the units get converted to a predefined unit.

In case yes, I am happy to provide our working code in a fork or via draft PR, for further refinement/incorporation.

Greetings

**Comment by tylerh111** [comment]
Thanks!

This would definitely be a good addition. I was able to get this to work without creating a new class by adding a `is_dimension` flag in the `PydanticPintQuantity` (which isn't all that great). I would like to make it seamlessly work with `PydanticPintQuantity` without that flag by just checking if the input is a dimension (because it's either going to be a units or dimensions).

A further suggestion to this idea is to take advantage of `pint.utils.UnitsContainer` which can convert from a string (e.g. `"[length] / [time]"`). We can do `self.ureg.get_dimensionality(dim)`. Still should be able to accept the dictionary `{"[length]": 1}`

I'm thinking something like that following (extended to what you have above).

```python
type Length = Annotated[PlainQuantity, PydanticPintQuantity("[length]")]

class Box(BaseModel):
    length: Length
    width: Length


box = Box(
    length="4 in",
    width="2 m",
)

print(box)
#> length=<Quantity(4, 'inch')> width=<Quantity(2, 'meter')>
```

---

Something interesting I noticed just now is how you used the type alias. I believe this creates a single shared ureg (as you didn't specify on in the constructor). Not sure if there's any adverse affects by doing this, but it's interesting nonetheless.

**Comment by tylerh111** [comment]
@lcnittl , let me know if the PR is what you're looking for.

You can do basically what you wrote above (using `PydanticPintQuantity` instead). You can use a dictionary `{"length": 1}` or a string `"[length]"`.

It is also possible to do something like `"[length] / [time]"`.

**Comment by lcnittl** [comment]
Hi @tylerh111 , thanks for the PR, and sorry for not getting back to you earlier. Yes, this is exactly what I was looking for, and even works as a drop-in replacement for our class (which has used `UnitContainer` as input type).

There is one more thing, but feel it should probably open another issue, since it goes in the opposite direction: A way to lock units to e.g. `cm` (i.e. only `cm` is accepted, `mm`, `in` or any other length will be rejected). Is this somthing tht might be considered? Happy to open a different issue in case it is.

Cheers

**Comment by tylerh111** [comment]
No worries, and great! I'll merge it in.

And yes, that should be a separate issue. It's nearly like `strict`, but that flag still allows conversions. Whereas, what you're proposing, you want no conversion. Adding an `exact` flag should do the trick.
